### ISSUE TITLE
Timecodes for "DE Zoomcamp Projects - Citibike Trips by Timur Kamaliev"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#112]
Youtube video: https://www.youtube.com/watch?v=Xvk7eXOb9LQ

**Comment by dimzachar** [comment]
0:00:00 - Building data pipeline for city bikes
0:03:26 - Data information, visualization creation, Google Cloud
0:06:56 - Create dashboards, configure infrastructure, orchestrate pipelines
0:10:24 - Optimize table creation with external data

**Comment by amitfrancis** [comment]
Updated, thanks!
