### ISSUE TITLE
Timecodes for "DE Zoomcamp Projects - GHCN-D by Marcos Jiménez"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#113]
Youtube video: https://www.youtube.com/watch?v=D9cQOefe5zA

**Comment by dimzachar** [comment]
0:00:00 - Data engineering project: weather analytics, technologies
0:02:56 - YouTube video creator explains project setup
0:06:14 - YouTube creator explains data ingestion pipeline
0:09:28 - Convert text files to CSV files
0:12:37 - Skip first row, average, faster analytics
0:15:35 - DAC submit, Spark transformations, BigQuery fact

**Comment by amitfrancis** [comment]
Updated, thanks!
