### ISSUE TITLE
Timecodes for "DE Zoomcamp Projects - DataTalksClub Slack Dump Analytics by Irem Ertürk"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#114]
Youtube video: https://www.youtube.com/watch?v=OkUMcyQzypg

**Comment by dimzachar** [comment]
0:00:04 - Capstone project presentation on YouTube
0:03:23 - Automating Google project setup with Airflow
0:06:24 - Automate composer environment setup with Terraform
0:09:37 - Terraform apply, manual step, GitHub
0:12:31 - Project completion, resource destruction, data analysis
0:15:57 - CSVs caused schema issues, data cleanup
0:19:02 - Course questions, network graphs, reactions, time
0:22:30 - Alex's visualization shows reactions and communication

**Comment by amitfrancis** [comment]
Updated, thanks!
