### ISSUE TITLE
Timecodes for "DE Zoomcamp Projects - Streamify by Ankur Chavda"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#115]
Youtube video: https://www.youtube.com/watch?v=vzoYhI8KTlY

**Comment by dimzachar** [comment]
0:00:00 - Data pipeline with multiple technologies
0:03:08 - Open port, setup Kafka, start
0:06:35 - Kafka Docker, events streaming, Spark
0:11:25 - Clone, export, setup, read, write
0:15:32 - Data storage, setup, airflow, bigquery
0:19:06 - Build state codes, join dimensions

**Comment by amitfrancis** [comment]
Updated, thank you!
