### ISSUE TITLE
Timecodes for "Homework #5 solution"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#123]
Youtube video: https://www.youtube.com/watch?v=3LK0elHi3fA

**Comment by dimzachar** [comment]
0:00:00 - Spark installation and data manipulation
0:03:44 - Spark version differences, compression, code execution
0:06:55 - Spark SQL query explanation
0:11:13 - Calculate trip duration using Spark
0:14:58 - Cast, sort, limit, longest trip
0:18:49 - SQL query stages: 2 or 3
0:22:43 - SQL join for common location pair
0:26:45 - Join, broadcast, common location, execute

**Comment by amitfrancis** [comment]
Updated, thank you!
