### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.6.3 - Setting up a Dataproc Cluster"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#124]
Youtube video: https://www.youtube.com/watch?v=osAiAYahvh8

**Comment by boisalai** [comment]
0:00 Setting up a Dataproc Cluster
0:39 Create a cluster
3:08 Submit a job from UI
7:27 Equivalent REST
7:56 Submit a job with gloud CLI

**Comment by boisalai** [comment]
These timecodes for 5.6.4 Connecting Spark to BigQuery
0:00 Connecting Spark to Big Query
0:37 BigQuery Connector to Spark
1:10 Modifying script to connect Spark with BigQuery
2:08 BigQuery schema name
2:55 gcloud dataproc 
3:15 Specify jar or not?
3:35 Upload script to Google Cloud Storage
4:05 Run the gcloud dataproc command

**Comment by amitfrancis** [comment]
Updated the timecodes for the two videos. Thanks!
