### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.6.1 - Connecting to Google Cloud Storage"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#126]
Youtube video: https://www.youtube.com/watch?v=Yyz293hBVcQ

**Comment by dimzachar** [comment]
0:00:00 - Returning to record Spark videos
0:00:50 - Setting up Spark for Google Cloud Storage
0:01:47 - Upload data to Google Cloud
0:02:36 - Parallel file upload using multi-threading
0:03:25 - Connect to Google Cloud Storage
0:04:14 - Downloading jar file for code leap
0:04:59 - Spark session setup and configuration
0:05:48 - Configuring Google Cloud Storage credentials
0:06:46 - Google Cloud file system implementation
0:07:39 - Connecting to Google Cloud Storage
