### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.5.2 - (Optional) Spark RDD mapPartition"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#127]
Youtube video: https://www.youtube.com/watch?v=k3uB2K99roI

**Comment by boisalai** [comment]
0:00 Spark RDD: mapPartitions
4:07 How to use .mapPartitions()
7:02 Turn partition to a pandas dataframe
9:37 Machine Learning

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
