### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.5.1 - (Optional) Operations on Spark RDDs"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#128]
Youtube video: https://www.youtube.com/watch?v=Bdu-xIrF3OM

**Comment by boisalai** [comment]
0:00 Operations on Spark RDDs
2:19 Create a new notebook
5:10 WHERE vs .filter()
7:10 GROUP BY vs .map()
12:10 Reduce by key
16:49 Unwrap the row
19:26 Turn back to a dataframe with schema
21:00 Save to parquet

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
