### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.4.1 - Anatomy of a Spark Cluster"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#131]
Youtube video: https://www.youtube.com/watch?v=68CipcZt7ZA

**Comment by dimzachar** [comment]
0:00:00 - Week five data engineering zoom comp.
0:00:50 - Setting up Spark context, real cluster.
0:01:44 - Spark cluster: master, jobs, submit, resources.
0:02:35 - Cluster has executors, master coordinates.
0:03:26 - Data frame partitions in Spark.
0:04:25 - Data redundancy in HDFS and Hadoop.
0:05:16 - Large files, small code, send code.
0:06:09 - S3 replaces Hadoop for data processing.

**Comment by amitfrancis** [comment]
Updated, thank you!
