### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.3.4 - SQL with Spark"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#132]
Youtube video: https://www.youtube.com/watch?v=uAlp2VuZZPY

**Comment by boisalai** [comment]
0:00 SQL with Spark
0:59 Read parquet files with Spark
2:21 Combine these two files into one
8:00 Querying with SQL
10:55 Save the results

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
