### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.3.2 - Spark DataFrames"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#134]
Youtube video: https://www.youtube.com/watch?v=ti3aC1m3rE8

**Comment by boisalai** [comment]
0:00 Spark DataFrames
1:38 Select
3:10 Actions vs Transformations
6:50 Functions avalaible in Spark
9:23 User defined functions

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
