### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.3.1 - First Look at Spark/PySpark"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#135]
Youtube video: https://www.youtube.com/watch?v=r_Sf6fCB40c

**Comment by boisalai** [comment]
0:00 First Look at Spark/PySpark
1:32 Create a new notebook
3:18 Read this file with Spark
4:43 Read the first rows of this file with pandas
6:08 Enforce a custom schema
10:18 Save as parquet files

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
