### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.2.1 - (Optional) Installing Spark on Linux"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#136]
Youtube video: https://www.youtube.com/watch?v=hqUbB9c8sKg

**Comment by boisalai** [comment]
0:00 (Optional) Installing Spark on Linux
0:39 Start VM
0:55 Installing Java
3:30 Installing Spark
6:45 bashrc
7:38 Start Jupyter 
8:00 Connect to the remote machine
8:32 Setup PySpark
11:59 Save to parquet
12:40 Open port and Spark UI

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
