### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.1.2 - Introduction to Spark"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#137]
Youtube video: https://www.youtube.com/watch?v=FhaqbEOuQ8U

**Comment by boisalai** [comment]
0:00 Introduction to Spark
1:30 High-level APIs
2:30 Spark for batch and streaming jobs
2:58 When to use Spark?
5:00 Workflow for Machine Learning

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
