### ISSUE TITLE
Timecodes for "DE Zoomcamp 5.1.1 - Introduction to Batch processing"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#138]
Youtube video: https://www.youtube.com/watch?v=dcHe5Fl3MF8

**Comment by boisalai** [comment]
0:00 What we will cover in this week.
1:30 Batch vs Streaming
3:37 Batch processing explained
4:15 Technologies
5:27 Orchestration tools
6:05 Advantages/disadvantages

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
