### ISSUE TITLE
Timecodes for "Week #4 Homework Solution (dbt)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#140]
Youtube video: https://www.youtube.com/watch?v=I_K0lNu9WQw

**Comment by dimzachar** [comment]
0:00:01 - Homework answers and data discrepancies
0:02:43 - Valid location pickup and drop
0:05:12 - Filter duplicates, analyze distribution, simplify
0:07:51 - Variable, schema, filter, model, dashboard

**Comment by amitfrancis** [comment]
Updated, thanks!
