### ISSUE TITLE
Timecodes for "DE Zoomcamp 4.5.2 - Visualising the data with Metabase (Alternative B)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#141]
Youtube video: https://www.youtube.com/watch?v=BnLkrA7a6gM

**Comment by dimzachar** [comment]
0:00:01 - Metabase: Free tool for visualizing data.
0:01:43 - Interactive data exploration with filters.
0:03:32 - Metadata, fact trips, tables, questions.
0:05:08 - Data type basics and filters.
0:06:54 - Self-explanatory data grouping and preview.
0:08:36 - Visualization options for data analysis.
0:10:25 - Customize settings for different options.
0:12:04 - Creating and customizing dashboards.
0:13:49 - Interactive dashboard editing and sharing.
0:15:28 - Dashboard refresh and customization options.

**Comment by amitfrancis** [comment]
Updated, thank you!
