### ISSUE TITLE
Timecodes for "DE Zoomcamp 4.5.1 - Visualising the data with Google Data Studio (Alternative A)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#142]
Youtube video: https://www.youtube.com/watch?v=39nLTs74A3E

**Comment by dimzachar** [comment]
0:00:01 - Data transformation and visualization process.
0:01:50 - Fields, aggregations, metrics, transformations, descriptions.
0:03:18 - Data freshness, data studio, dimensional modeling, fact table, change table name, create report, time series graphs.
0:04:55 - Trips per day, service type, data filtering, date range controls.
0:06:50 - Data selection and customization options.
0:09:08 - Changing styles and dimensions in charts.
0:10:54 - Data analysis and visualization options.
0:12:36 - Trips per month, filter by pickup month.
0:14:49 - Comparing 2020 and 2019 visually.
0:17:29 - Customize grid, add titles, filters.

**Comment by amitfrancis** [comment]
Updated, thank you!
