### ISSUE TITLE
Timecodes for "DE Zoomcamp 4.4.2 - Deployment Using dbt Locally (Alternative B)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#143]
Youtube video: https://www.youtube.com/watch?v=Cs9Od1pcrzM

**Comment by dimzachar** [comment]
0:00:00 - Deploying DVT project using version control and CI/CD.
0:01:07 - Dev workflow for production deployment.
0:02:13 - Multiple commands, separate logs, scheduling.
0:03:12 - Data sources, freshness, threshold, deployment, continuous integration.
0:04:21 - GitHub PR webhook and DVT cloud run.
0:05:24 - Creating multiple profiles for development.

**Comment by amitfrancis** [comment]
Updated, thanks!
