### ISSUE TITLE
Timecodes for "DE Zoomcamp 4.4.1 - Deployment Using dbt Cloud (Alternative A)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#144]
Youtube video: https://www.youtube.com/watch?v=rjf6yZNGX8I

**Comment by dimzachar** [comment]
0:00:00 - Deploying DVT project using version control and CI/CD.
0:01:54 - Scheduler for running commands in DVT Cloud.
0:03:38 - Deployment process with DVT Cloud.
0:05:21 - Creating protected branches and environments.
0:07:03 - Creating shop with DVT build.
0:08:43 - Successful job with detailed logs.
0:10:37 - Data catalog overview and code.
0:12:14 - Google Cloud documentation and project management.

**Comment by amitfrancis** [comment]
Updated, thank you!
