### ISSUE TITLE
Timecodes for "DE Zoomcamp 4.3.2 - Testing and Documenting the Project"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#145]
Youtube video: https://www.youtube.com/watch?v=UishFmq1hLM

**Comment by dimzachar** [comment]
0:00:01 - Creating models, views, macros, packages, testing, and documentation.
0:01:39 - Column tests for data validation.
0:03:14 - Generate project documentation as website.
0:04:57 - Defining model documentation and tests.
0:06:37 - Testing taxi payment type variables.
0:08:22 - Variable values defined, filter, run tests.
0:09:55 - Testing model assumptions, copying missing data.
0:11:38 - Running YouTube field and completing project

**Comment by amitfrancis** [comment]
Updated timecodes! Thanks
