### ISSUE TITLE
Timecodes for "DE Zoomcamp 4.3.1 - Build the First dbt Models"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#146]
Youtube video: https://www.youtube.com/watch?v=UVI30Vxzd6c

**Comment by geraldooi** [comment]
This video already has timecodes.

00:00 Anatomy of a dbt model 
03:15 The FROM clause: Sources and seeds
06:40 The FROM clause: ref macro
08:38 Define a source and develop the first model (stg_green_tripdata)
17:24 Definition and usage of macros 
24:10 Importing and using dbt packages
29:18 Definition of variables and setting a variable from the cli
33:33 Add second model (stg_yellow_tripdata)
35:16 Creating and using dbt seed (taxi_zones_lookup and dim_zone)
41:20 Unioning our models in fact_trips and understanding dependencies
