### ISSUE TITLE
Timecodes for "DE Zoomcamp 4.1.2 - What is dbt"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#149]
Youtube video: https://www.youtube.com/watch?v=4eCouvVOJUw

**Comment by joeeoj** [comment]
00:00 What is dbt?
01:03 How does dbt work?
02:04 How to use dbt?
03:30 How are we going to use dbt?

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by alexeygrigorev** [comment]
Thanks Mike!

**Comment by amitfrancis** [comment]
Thanks!
