### ISSUE TITLE
Timecodes for "DE Zoomcamp 4.1.1 - Analytics Engineering Basics"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#150]
Youtube video: https://www.youtube.com/watch?v=uF76d5EmdtU

**Comment by joeeoj** [comment]
00:00 1 - What is Analytics Engineering?
00:17 Data domain developments
01:02 Roles in a data team
02:20 Tooling
03:06 2 - Data modeling concepts
03:11 ETL vs ELT
04:12 Kimball's Dimensional Modeling
05:05 Elements of Dimensional Modeling
05:50 Architecture of Dimensional Modeling

**Comment by amitfrancis** [comment]
Updated timecodes
