### ISSUE TITLE
Timecodes for "Data Engineering Zoomcamp Week #4 Office Hours"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#151]
Youtube video: https://www.youtube.com/watch?v=U7iBBV8Dn74

**Comment by dimzachar** [comment]
0:00:00 - Week 4 project announcement, videos available
0:02:20 - Data pipeline for changing database
0:05:13 - Database changes in data warehouse
0:07:37 - Capture database changes for analysis
0:10:10 - AWS vs GCP popularity comparison
0:12:46 - AWS popular, GCP catching up
0:15:23 - Follow videos, do queries, get data
0:18:02 - Homework, transformation, analytics, cleaning, models
0:20:50 - AWS Athena, SageMaker, Jupyter Notebooks
0:23:41 - Difficulties make us stronger
0:26:16 - Git, Python, SQL, overwhelming, road map
0:28:51 - Projects, certificates, resources, books, courses
0:31:21 - Kubernetes alternatives for stateful apps
0:34:27 - Data engineering complexity and importance
0:36:59 - Python, SQL, data modeling, data warehousing, analytics
0:39:22 - Data engineer discovers new tool
0:41:59 - Upload green taxi data, data sets
0:44:50 - Course progress sharing in Germany
0:47:22 - German not required for jobs
0:49:47 - Data engineering outsourcing trends 2022
0:52:39 - Kubernetes helpful for debugging jobs
0:55:22 - Incorporate URL, change grading script
0:58:23 - DBT roadmap: data cataloging, governance

**Comment by amitfrancis** [comment]
Updated, thank you!
