### ISSUE TITLE
Timecodes for "DE Zoomcamp 3.4.1 - Homework"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#152]
Youtube video: https://www.youtube.com/watch?v=YtRtR2iTWR4

**Comment by joeeoj** [comment]
00:00 Introduction
00:10 Question 1
02:36 Question 2
03:55 Question 3
04:44 Question 4
08:55 Question 5
09:54 Question 6
10:56 Question 7

**Comment by amitfrancis** [comment]
Updated timecodes
