### ISSUE TITLE
Timecodes for "DE Zoomcamp 3.3.3 - Integrating BigQuery with Airflow (+ Week 2 Review)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#153]
Youtube video: https://www.youtube.com/watch?v=lAxAhHNeGww

**Comment by dimzachar** [comment]
0:00:02 - Automating steps, extending airflow pipeline
0:03:15 - Unnecessary services, single node setup
0:06:33 - Developing concepts, data injection, parallelization
0:10:11 - Custom setup with multiple containers
0:13:45 - Import libraries, variables, and constants
0:17:58 - Reorganize files using GCS
0:21:38 - GCS task and file movement
0:26:08 - Sorting data, creating external table
0:30:08 - Create partitioned table based on external table
0:34:08 - External data errors, directory fix
0:39:15 - Schema error in external data
0:43:00 - External data configuration and operators
0:47:56 - Workflow steps, file reorganization, query performance

**Comment by amitfrancis** [comment]
Updated! Thank you!
