### ISSUE TITLE
Timecodes for "DE Zoomcamp 3.3.2 - BigQuery Machine Learning Deployment"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#154]
Youtube video: https://www.youtube.com/watch?v=BjARzEWaznU

**Comment by dimzachar** [comment]
0:00:01 - Exporting ML model to Docker image.
0:01:24 - Creating serving directory, copying tip model data.
0:02:59 - Container running, Postman for HTTP requests, version check, prediction request.

**Comment by amitfrancis** [comment]
Updated! Thank you!
