### ISSUE TITLE
Timecodes for "DE Zoomcamp 3.3.1 - BigQuery Machine Learning"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#155]
Youtube video: https://www.youtube.com/watch?v=B-WtpB0PuG4

**Comment by dimzachar** [comment]
0:00:00 - Advanced machine learning in BigQuery tutorial
0:02:07 - Steps in ML development: data collection, processing, model building, validation, deployment.
0:04:19 - Building linear regression model with selected columns.
0:06:28 - BigQuery's automatic feature preprocessing explained in detail.
0:08:55 - Creating table with string columns for ML.
0:11:34 - Model evaluation and feature information in BigQuery.

**Comment by amitfrancis** [comment]
Updated! Thank you so much!
