### ISSUE TITLE
Timecodes for "DE Zoomcamp 3.2.2 - Internals of Big Query"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#156]
Youtube video: https://www.youtube.com/watch?v=eduHi1inM4s

**Comment by joeeoj** [comment]
00:00 Introduction
00:34 Internals
02:46 Columnar and record oriented storage
03:57 Dremel
05:46 References

And here are the references listed on the last slide if you want to add them to the video description:

* https://cloud.google.com/bigquery/docs/how-to
* https://research.google/pubs/pub36632/
* https://panoply.io/data-warehouse-guide/bigquery-architecture/
* https://www.goldsborough.me/distributed-systems/2019/05/18//21-09-00-a_look_at_dremel/

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thanks!
