### ISSUE TITLE
Timecodes for "DE Zoomcamp 3.2.1 - BigQuery Best Practices"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#157]
Youtube video: https://www.youtube.com/watch?v=k81mLJVX08w

**Comment by geraldooi** [comment]
0:00 Introduction
0:24 Avoid SELECT *
1:06 Price your queries before running them
1:14 Use clustered or partitioned tables
1:22 Use streaming inserts with caution
1:31 Materialize query results in stages
1:56 Best Practice of Query Performance 1
2:41 Best Practice of Query Performance 2

**Comment by amitfrancis** [comment]
Updated timecodes. Thank you!
