### ISSUE TITLE
Timecodes for "DE Zoomcamp 3.1.2 - Partioning and Clustering"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#158]
Youtube video: https://www.youtube.com/watch?v=-CqXf7vhhDs

**Comment by joeeoj** [comment]
00:00 Introduction
00:12 BigQuery partition
01:36 BigQuery clustering
03:13 Partitioning vs clustering
04:59 Clustering over partitioning
06:02 Automatic reclustering
07:03 Recap

**Comment by amitfrancis** [comment]
Updated timecodes
