### ISSUE TITLE
Timecodes for "DE Zoomcamp 3.1.1 - Data Warehouse and BigQuery"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#159]
Youtube video: https://www.youtube.com/watch?v=jrHljAoD6nM

**Comment by joeeoj** [comment]
00:00 Agenda
00:28 OLAP vs OLTP
02:18 What is a data warehouse
03:36 BigQuery
05:19 BigQuery interface
07:04 Querying public datasets
07:42 BigQuery costs
09:02 Create an external table
12:04 Partitioning
18:45 Clustering

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thanks!
