### ISSUE TITLE
Timecodes for "Data Engineering Zoomcamp Week #3 Office Hours"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#160]
Youtube video: https://www.youtube.com/watch?v=yZ-d7nItpB8

**Comment by dimzachar** [comment]
0:00:07 - Clarify future weeks and deadlines
0:02:59 - Partitioning, best practices, advanced videos
0:05:20 - GCP market, workshop, homework, hoodie
0:08:07 - Week two homework format: Google form, code link, random checks
0:10:42 - Useful for learning and practice
0:13:06 - Postgres for transactions, not analytics
0:15:47 - Merge videos for best practices
0:18:49 - Airflow: Resource-intensive orchestration for jobs
0:21:19 - More pipelines, workflows, orchestration tools
0:23:52 - Docker Compose simplifies container deployment
0:26:32 - Airflow deployment options: native, cloud-based
0:29:16 - Kubernetes operator for Airflow
0:32:03 - Docker problems, plan for NoSQL
0:34:50 - Local setup complexity, cloud-based option
0:37:17 - Phone works better than computer
0:39:59 - BigQuery: Upload, append, and structure
0:42:17 - Weekly video summaries for better understanding
0:44:59 - GitHub homework confusion, yellow taxis
0:48:11 - Computer froze executing parallel jobs
0:51:11 - Separate courses, useful for envelopes
0:54:16 - Future iterations: same videos, different homework
0:57:03 - Inspire, course, memory, docker, airflow

**Comment by amitfrancis** [comment]
Updated, thanks!
