### ISSUE TITLE
Timecodes for "DE Zoomcamp 2.1.1 - Data Lake"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#169]
Youtube video: https://www.youtube.com/watch?v=W3Zm6rjOq70

**Comment by joeeoj** [comment]
0:04 Agenda
0:17 What is a Data Lake?
1:20 Data Lake vs Data Warehouse
2:12 How did Data Lake start?
3:39 ETL vs ELT
4:37 Gotchas of Data Lake
6:10 Cloud provider Data Lake

**Comment by amitfrancis** [comment]
Updated timecodes
