### ISSUE TITLE
Timecodes for "Week #1 Homework Solution (SQL)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#171]
Youtube video: https://www.youtube.com/watch?v=HxHqH2ARfxM

**Comment by joeeoj** [comment]
0:13 Question 3: Count records
1:01 Question 4: Largest tip
2:42 Question 5: Most popular destination
6:07 Question 6: Most expensive route

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thanks :)
