### ISSUE TITLE
Timecodes for "DE Zoomcamp 1.4.2 - Port Mapping and Networks in Docker (Bonus)"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#172]
Youtube video: https://www.youtube.com/watch?v=tOr4hTsHOzU

**Comment by Ashish-Soni08** [comment]
i am on it

**Comment by dimzachar** [comment]
0:00:01 - Setting up Docker network and containers.
0:02:49 - Port mapping and forwarding in Docker.
0:05:36 - Executing commands, connecting to database, running script.
0:08:15 - Timestamp:  -  Description: Solving permission issues with Docker volumes.
0:11:01 - Modifying address and network for Docker.

**Comment by amitfrancis** [comment]
Updated timecodes! Thanks
