### ISSUE TITLE
Timecodes for "DE Zoomcamp 1.3.2 - Creating GCP Infrastructure with Terraform"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#174]
Youtube video: https://www.youtube.com/watch?v=dNkEgO-CExg

**Comment by joeeoj** [comment]
0:20 .terraform-version
1:04 main.tf
1:23 terraform declaration
3:25 provider plugins
4:00 resource example - google_storage_bucket
5:42 provider credentials
6:34 variables.tf
10:54 overview of terraform commands
13:35 running terraform commands
18:08 recap

**Comment by dimzachar** [comment]
0:00:00 - Configuring Terraform files: version, resources, and storage.
0:02:27 - Importing and implementing predefined module definitions.
0:04:48 - YouTube Explanation of variables and resources.
0:06:56 - Understanding local variables and project regions.
0:09:08 - Timestamp:  - Explaining regional communication and variables.
0:11:14 - Explanation of Terraform's destroy command.
0:13:22 - Initializing configuration and importing plugins for Google provider.
0:15:32 - Creating resources with Terraform plan and apply.

**Comment by amitfrancis** [comment]
Thanks! Timecodes updated
