### ISSUE TITLE
Timecodes for "DE Zoomcamp 1.3.1 - Introduction to Terraform Concepts & GCP Pre-Requisites"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#175]
Youtube video: https://www.youtube.com/watch?v=Hajwnmj0xfQ

**Comment by Isaac-Tolu** [comment]
00:00  Introduction
00:35  What is Terraform?
01:10  What is IaC?
01:43  Advantages of IaC
02:28  Installing Terraform
02:51  GCP Setup: Introduction
04:06  GCP Setup: Creating a Project
05:26  GCP Setup: Creating a Service Account
08:45  GCP Setup: Installing Google SDK
10:29  GCP Setup: Authentication of Google Application Credentials
14:48  More on Installing Terraform
15:43  Creating Infrastructure with Terraform: Introduction
17:26  Creating Infrastructure with Terraform: Setting up IAM roles
20:20  Creating Infrastructure with Terraform: Enabling APIs

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thank you :)
