### ISSUE TITLE
Timecodes for "DE Zoomcamp 1.2.6 - SQL Refreshser"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#176]
Youtube video: https://www.youtube.com/watch?v=QEcps_iskgg

**Comment by Isaac-Tolu** [comment]
00:00 Introduction
00:59 Joining yellow taxi table with the zones lookup table (implicit inner join)
05:20 Using an explicit inner join
06:05 Checking for records with Location ID not in the zones table
06:45 Checking for Location IDs in the zones table not in the yellow taxi table
07:51 Using Left, Right and Outer Joins when some Location IDs are not in either tables
10:53 Using GROUP BY to calculate number of trips per day
12:20 Using ORDER BY to order the results of your query
13:27 Other kinds of aggregations
14:03 Grouping by multiple fields
15:26 Closing

**Comment by amitfrancis** [comment]
Updated timecodes

**Comment by amitfrancis** [comment]
Thank you :)
