### ISSUE TITLE
Timecodes for "DE Zoomcamp 1.2.5 - Running Postgres and pgAdmin with Docker-Compose"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#177]
Youtube video: https://www.youtube.com/watch?v=hKI6PkPhpa0

**Comment by Isaac-Tolu** [comment]
00:00  Introduction and Revision of last video
01:04  Introduction to Docker-Compose
01:22  Installing Docker-Compose
01:56  Configuration of postgres database and pgadmin in Docker-Compose file
05:51  Running the Docker-Compose file
06:27  Connecting to pgadmin and configuration
07:13  Running test query on pgadmin
07:34  Stopping the running containers with Docker-Compose
07:50  Running Docker-Compose in detached mode
08:19  Closing

**Comment by amitfrancis** [comment]
Updated timecodes!

**Comment by amitfrancis** [comment]
Thank you! Just updated the timecodes :)
