### ISSUE TITLE
Timecodes for "DE Zoomcamp 1.2.2 - Optional: Connecting to Postgres with Jupyter and Pandas"

### ISSUE THREAD

**Issue by alexeygrigorev** [DataTalksClub/data-engineering-zoomcamp#180]
Youtube video: https://www.youtube.com/watch?v=3IkfkTwqHx4

**Comment by Isaac-Tolu** [comment]
00:00 Introduction
00:31 Connecting to Postgres instance with SQLAlchemy
03:39 Using pandas to execute SQL statements on the database
05:36 Using pandas to insert yellow trip-data datarame into the database
06:15 Using pandas to execute SQL queries on the yellow trip-data database table
07:04 Closing

**Comment by amitfrancis** [comment]
Updated timecodes! Thanks

**Comment by amitfrancis** [comment]
Updated the timecodes! Thanks Toluwani :)
