### ISSUE TITLE
networking for docker-compose.yaml is not available

### ISSUE THREAD

**Issue by giuliosmall** [DataTalksClub/data-engineering-zoomcamp#207]
In week 1, we are supposed to create a network to connect `pgadmin` to `postgres` database.

Alexey shows how to do it from CLi, which is the less recommended way if we want to keep the network bridge available for the future.

I did some research online but want able to find a solution. Is it possibile to update `docker-compose.yaml` with the above specification please?

**Comment by TheHollidayInn** [comment]
Docker compose creates a default network and uses the services names as alias to the internal IPs.

So to connect the two:
- copy the docker-compose.yml
- run `docker-compose up`
- open `http://localhost:8080`
- login with the user pass in the env variables inside the docker compose file for pgadmin
- Add a server and use the following. Notice that I use `pgdatabase` as the hostname as docker will resolve that internally to the postgres server.

![Screenshot 2022-08-16 121808](https://user-images.githubusercontent.com/1253400/184950656-8af85a53-a612-450d-913c-b872cb1f2f24.png)

**Comment by giuliosmall** [comment]
@TheHollidayInn Thanks for the support! 

Does it mean once the network is created, there is no need to specify additional parameters in `docker-compose.yaml`?

**Comment by TheHollidayInn** [comment]
No problem! I'm pretty sure when using docker compose in a file it will create a default network: https://docs.docker.com/compose/networking/

> By default Compose sets up a single [network](https://docs.docker.com/engine/reference/commandline/network_create/) for your app. Each container for a service joins the default network and is both reachable by other containers on that network, and discoverable by them at a hostname identical to the container name.


But you can create additional networks if you need to separate other services. For this flow it isnt needed.

**Comment by giuliosmall** [comment]
Thanks @TheHollidayInn, much appreciated indeed!

This mean that each sub-container is not a closed box, but they share a common default network! Hence there is no need to manually create a bridge between the two of them, right?

**Comment by TheHollidayInn** [comment]
Yes, that is my interpretation. 

And if you want to have a larger compose, you can create networks to segment the services, but by default they get added to the default network.

**Comment by giuliosmall** [comment]
@TheHollidayInn thanks! Shall I close this issue now? What do you think about it?
