### ISSUE TITLE
Pip install very slow in docker

### ISSUE THREAD

**Issue by sreesanjeevkg** [DataTalksClub/data-engineering-zoomcamp#223]
I was trying to do a pip install of pandas on my docker and it is very slow. I have attached image below for reference

<img width="832" alt="Screenshot 2023-01-06 at 7 46 13 PM" src="https://user-images.githubusercontent.com/32449066/211030858-f4f0b879-c879-4379-b2ea-d20a00cafcbe.png">

Can anybody provide any assistance on how to speed it up. My network does not seem to be the issue.

**Comment by digitalghost-dev** [comment]
What does your Dockerfile look like?

**Comment by alexeygrigorev** [comment]
Please use slack to ask questions
