### ISSUE TITLE
Installation of dependencies to apache airflow.

### ISSUE THREAD

**Issue by CollinsKCollins** [DataTalksClub/data-engineering-zoomcamp#256]
![error](https://user-images.githubusercontent.com/123388009/214068908-8b688e26-0678-4edf-98de-0b938e5bfc9f.JPG)
I've been trying to install some dependencies to apache airflow but run into this error shown in the image. I have tried scouring to the available online communities but haven't had any luck. Is this issue only unique to apache 2.5.0?

**Comment by CollinsKCollins** [comment]
Any help will be greatly appreciated.

**Comment by iobruno** [comment]
@CollinsKCollins  As per the community guidelines, and as Alexey said in the video, you should asking this in the Slack channel #course-data-engineering and not opening issues for that.

**Comment by CollinsKCollins** [comment]
> @CollinsKCollins As per the community guidelines, and as Alexey said in the video, you should asking this in the Slack channel #course-data-engineering and not opening issues for that.

I stand guided.
