### ISSUE TITLE
Ubuntu error with pgcli solution

### ISSUE THREAD

**Issue by rafaeljcd** [DataTalksClub/data-engineering-zoomcamp#262]
![image](https://user-images.githubusercontent.com/123484899/214539805-25e61fe5-c6ba-4240-bb54-f76700bb0ece.png)

As you can see there, running the pgcli at ubuntu sometimes will cause an error even after installing the library
`pip install psycopg2-binary`

The solution to this can be found from this [Stackoverflow answer](https://stackoverflow.com/a/64565388/14859274)

`sudo apt-get install libpq-dev`

And then you'll be able to use the pgcli.

If possible to add this to the FAQs

**Comment by alexeygrigorev** [comment]
Yes please add it to FAQ
