### ISSUE TITLE
variables.tf missing default and type vars

### ISSUE THREAD

**Issue by gregorysprenger** [DataTalksClub/data-engineering-zoomcamp#264]
Within terraform section of week 1, variables.tf only lists:

```
variables project {
  description = "Your GCP Project ID"
}
```

Per the markdown file for windows, other information is specified and I believe it is needed for other users on other OS (tested on Ubuntu 22.04).

```
variables project {
  description = "Your GCP Project ID"
  default = "Your actual GCP Project ID"
  type = string
}
```

**Comment by bsenst** [comment]
here the link to the corresponding [variables.tf](https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/week_1_basics_n_setup/1_terraform_gcp/terraform/variables.tf) file
