### ISSUE TITLE
Timecodes for "DE Zoomcamp 2.2.2 - Introduction to Prefect concepts"

### ISSUE THREAD

**Issue by iobruno** [DataTalksClub/data-engineering-zoomcamp#269]
**[Updated]** Youtube video: https://youtu.be/cdtN6dhp708

**Comment by iobruno** [comment]
0:00 Introduction to the Scenario
0:50 Condaenv and Installing dependencies for Prefect
2:00 Recap: ingest_data.py and pgAdmin
4:45 Introduction to Workflow Orchestration
5:18 Transform the Script into a Prefect Flow 
8:45 Running your first Prefect Flow
9:16 Prefect Tasks for Extract and Transform
14:21 Prefect Task for Loading Data into Postgres
16:57 Prefect Flow: Parameterization & Subflows
19:54 Quick Tour over Prefect Orion UI
23:18 Overview of Task Run Concurrency & Notifications
24:49 Overview of Prefect Blocks
25:48 Prefect Blocks with SQLAlchemy

**Comment by iobruno** [comment]
0:00 Introduction
0:50 Condaenv and Installing dependencies for Prefect
2:00 Recap: 'ingest_data.py' and pgAdmin
4:45 Introduction to Workflow Orchestration
5:17 Transform the Script into a Prefect Flow 
8:45 Running your first Prefect Flow
9:16 Prefect Tasks for Extract and Transform
14:23 Prefect Task for Loading Data into Postgres
16:57 Prefect Flow: Parameterization & Subflows
19:54 Quick Tour over Prefect Orion UI
23:18 Overview of Task Run Concurrency & Notifications
24:49 Overview of Prefect Blocks
25:47 Prefect Blocks with SQLAlchemy

**Comment by alexeygrigorev** [comment]
Thanks Bruno! We have updated the video with larger fonts: https://youtu.be/cdtN6dhp708

If it's not too much trouble for you, could you update the timecodes for the new video?

**Comment by iobruno** [comment]
Sure, I'm on it

**Comment by iobruno** [comment]
0:00 Introduction 
0:15 Recap: 'ingest_data.py' and pgAdmin
1:34 Scenario explanation
2:07 Create a Virtualenv and Install Dependencies
3:44 Recap: 'ingest_data.py' and pgAdmin
5:02 Transform the Script into a Prefect Flow
9:36 Running your first Prefect Flow
10:10 Prefect Task: Extract Data
14:54 Prefect Task: Transform / Data Cleanup
17:57 Prefect Task: Load Data into Postgres
22:05 Prefect Flow: Parameterization & Subflows
24:47 Prefect Orion: Quick Tour through the UI
26:27 Overview of Notifications & Task Run Concurrency
27:20 Overview of Prefect Blocks
28:34 Prefect Blocks: SQLAlchemy - Part I
29:22 Prefect Collections Catalog
29:50 Prefect Blocks: SQLAlchemy - Part II
34:12 Wrapping up & Review

**Comment by iobruno** [comment]
@alexeygrigorev There you go

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks, Bruno!
