### ISSUE TITLE
Timecodes for "DE Zoomcamp 2.2.3 - ETL with GCP & Prefect"

### ISSUE THREAD

**Issue by iobruno** [DataTalksClub/data-engineering-zoomcamp#270]
Youtube video: https://www.youtube.com/watch?v=W-rMz_2GwqQ

**Comment by iobruno** [comment]
0:00 Introduction
0:23 Setting up up the environment
2:53 Scenario explanation
3:37 Prefect Flow: pandas DataFrame to Google Cloud Storage
7:18 Prefect Task: Extract Dataset from the Web with retries
11:52 Prefect Task: Data Cleanup
17:16 Prefect Task: Write to Local Filesystem
21:08 Prefect Task: Write to GCS - Part I
22:05 Google Cloud Storage: Intro & Browsing
24:09 Prefect Blocks: GCS Bucket
26:14 Prefect Blocks: GCP Credentials & Service Account
29:53 Prefect Blocks: Write to GCS - Part II
34:04 Wrapping up & Review

**Comment by iobruno** [comment]
0:00 Introduction
0:23 Setting up up the environment
2:53 Scenario explanation
3:37 Prefect Flow: pandas DataFrame to Google Cloud Storage
7:18 Prefect Task: Extract Dataset from the Web with retries
11:52 Prefect Task: Data Cleanup
17:16 Prefect Task: Write to Local Filesystem
21:08 Prefect Task: Write to GCS - Part I
22:05 Google Cloud Storage: Overview & Browsing
24:09 Prefect Blocks: GCS Bucket
26:14 Prefect Blocks: GCP Credentials & Service Account
29:53 Prefect Blocks: Write to GCS - Part II
34:04 Wrapping up & Review

**Comment by iobruno** [comment]
0:00 Introduction
0:23 Setting up up the environment
2:53 Scenario explanation
3:37 Prefect Flow: pandas DataFrame to Google Cloud Storage
7:18 Prefect Task: Extract Dataset from the Web with retries
11:52 Prefect Task: Data Cleanup
17:16 Prefect Task: Write to Local Filesystem
21:08 Prefect Task: Write to GCS - Part I
22:05 Google Cloud Storage: Overview
24:09 Prefect Blocks: GCS Bucket
26:14 Prefect Blocks: GCP Credentials & Service Account
29:53 Prefect Blocks: Write to GCS - Part II
34:04 Wrapping up & Review

**Comment by iobruno** [comment]
0:00 Introduction 
0:15 Recap: 'ingest_data.py' and pgAdmin
1:34 Scenario explanation
2:07 Create a Virtualenv and Install Dependencies
3:44 Recap: 'ingest_data.py' and pgAdmin
5:02 Transform the Script into a Prefect Flow
9:36 Running your first Prefect Flow
10:10 Prefect Task: Extract Data
14:54 Prefect Task: Transform / Data Cleanup
17:57 Prefect Task: Load Data into Postgres
22:05 Prefect Flow: Parameterization & Subflows
24:47 Prefect Orion: Quick Tour through the UI
26:27 Overview of Notifications & Task Run Concurrency
27:20 Overview of Prefect Blocks
28:34 Prefect Blocks: SQLAlchemy - Part I
29:22 Prefect Collections Catalog
29:50 Prefect Blocks: SQLAlchemy - Part II
34:12 Wrapping up & Review

**Comment by amitfrancis** [comment]
Updated timecodes! Thank you

**Comment by iobruno** [comment]
@amitfrancis Um... I think the timecodes set for the [2.2.3 Video](https://www.youtube.com/watch?v=W-rMz_2GwqQ) are using the ones I have set for the 2.2.2, instead

**Comment by amitfrancis** [comment]
Done! I changed it

**Comment by iobruno** [comment]
@amitfrancis we might need to revisit this one once again :(

The 2.2.3 video is still using the timecodes from the 2.2.2 

At least that's what it looks like on my end here: https://www.youtube.com/watch?v=W-rMz_2GwqQ

**Comment by amitfrancis** [comment]
Apologies! I just removed the timecodes for 2.2.3. I'm reopening this again

**Comment by iobruno** [comment]
No problem at all! Timecodes should be these ones:

0:00 Introduction
0:23 Setting up up the environment
2:53 Scenario explanation
3:37 Prefect Flow: pandas DataFrame to Google Cloud Storage
7:18 Prefect Task: Extract Dataset from the Web with retries
11:52 Prefect Task: Data Cleanup
17:16 Prefect Task: Write to Local Filesystem
21:08 Prefect Task: Write to GCS - Part I
22:05 Google Cloud Storage: Overview
24:09 Prefect Blocks: GCS Bucket
26:14 Prefect Blocks: GCP Credentials & Service Account
29:53 Prefect Blocks: Write to GCS - Part II
34:04 Wrapping up & Review

**Comment by amitfrancis** [comment]
Thank you!
