### ISSUE TITLE
Timecodes for "DE Zoomcamp 2.2.4 - From Google Cloud Storage to Big Query"

### ISSUE THREAD

**Issue by iobruno** [DataTalksClub/data-engineering-zoomcamp#271]
Youtube video: https://www.youtube.com/watch?v=Cx5jt-V5sgE

**Comment by iobruno** [comment]
0:00 Recap and Scenario explanation
0:22 Prefect Flow: GCS to BigQuery
2:24 Prefect Task: Extract from GCS
8:33 Prefect Task: Data Transformation
12:19 Prefect Task: Load into BigQuery - Part I
14:07 BigQuery: Overview & Data Import from GCS
17:10 Prefect Task: Load into BigQuery - Part II
20:13 BigQuery: Querying the Data
20:49 Wrapping up & Review

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
