### ISSUE TITLE
Timecodes for "DE Zoomcamp 2.2.5 - Parametrizing Flow & Deployments with ETL into GCS flow"

### ISSUE THREAD

**Issue by iobruno** [DataTalksClub/data-engineering-zoomcamp#272]
Youtube video: https://www.youtube.com/watch?v=QrDxPjX10iw

**Comment by iobruno** [comment]
0:00 Introduction
0:18 Prefect Flows: Parameterized Flow
2:00 Prefect Flows: Orchestrating Subflows with a Parent Flow
4:06 Prefect Task: Caching Strategy for Fetching CSVs from Web
4:55 Manually Running the Flow (Web to GCS)
6:43 Prefect Deployment: Overview
8:43 Prefect Deployment: Build & Apply
11:43 Prefect Deployments on Prefect Orion UI 
13:16 Prefect Work Queues and Agents 
15:20 Prefect Notifications
17:06 Wrapping up & Review

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
