### ISSUE TITLE
Timecodes for "DE Zoomcamp 2.2.6 - Schedules & Docker Storage with Infrastructure"

### ISSUE THREAD

**Issue by iobruno** [DataTalksClub/data-engineering-zoomcamp#273]
Youtube video: https://www.youtube.com/watch?v=psNSzqTsi-s

**Comment by iobruno** [comment]
0:00 Introduction
0:08 Scheduling Flows on Orion UI
2:11 Scheduling when creating Deployments (via CLI)
4:34 Scheduling after you've created a Deployment (via CLI)
5:03 Running Prefect Flows on Docker Containers
6:30 Docker Containers: Dockerfile, Build and Publish 
11:52 Prefect Blocks: Docker Container
14:00 Prefect Deployment from a Python Script
18:20 Prefect Profiles (Docker Container <> Orion Server Integration)
20:03 Prefect Agent & Workflow run in a Docker Container
23:29 Wrapping up & Review

**Comment by amitfrancis** [comment]
Updated timecodes Thanks!
