### ISSUE TITLE
Timecodes for "DE Zoomcamp 2.2.7 - Prefect Cloud/Additional resources"

### ISSUE THREAD

**Issue by iobruno** [DataTalksClub/data-engineering-zoomcamp#274]
Youtube video: https://www.youtube.com/watch?v=gGC23ZK7lr8

**Comment by iobruno** [comment]
0:00 Introduction
0:14 Overview of Prefect Learning Resources
0:41 Prefect Cloud (Self-Managed Service)
1:59 GCP and Prefect Cloud Guides by Anna Geller
2:22 Prefect Community on Slack and Discourse
2:46 Prefect Helm Charts for K8s and GitHub

**Comment by amitfrancis** [comment]
Updated timecodes. Thanks!
