### ISSUE TITLE
Week 4 - Dataset link ain't working

### ISSUE THREAD

**Issue by Hfelipini** [DataTalksClub/data-engineering-zoomcamp#307]
Hello, everybody.

Today I was starting the week 4 but I couldn't download the dataset, the link to the repository is leading to a 404 error.
Could you fix it?

Thanks and best regards,
Henrique Felipini

![image](https://user-images.githubusercontent.com/22395461/218605918-7169edf8-f0a3-49d8-87ce-dba8cda4fdce.png)
--------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/22395461/218606142-7b3658e4-5139-4b45-b568-34470ad7a435.png)

**Comment by bsenst** [comment]
@alexeygrigorev I think this issue can be closed as the link to the dataset was replaced by a link to the list of datasets https://github.com/DataTalksClub/nyc-tlc-data/

**Comment by alexeygrigorev** [comment]
Thank you!
