### ISSUE TITLE
Invalid dbt_cloud_setup.md link in Week4 (streamlit)

### ISSUE THREAD

**Issue by sukurocking** [DataTalksClub/data-engineering-zoomcamp#384]
In the streamlit-hosted site, observed that in the section for dbt cloud setup, dbt_cloud_setup.md is linked to invalid url. 

streamlit section link: https://dezoomcamp.streamlit.app/~/+/Week_4_Analytics_Engineering#setting-up-dbt-for-using-bigquery-alternative-a-preferred
invalid url: https://dezoomcamp.streamlit.app/~/+/dbt_cloud_setup.md
suggested url: https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/40b07b43b9f6edf2af1d5613fc19b2704c6ef0bd/week_4_analytics_engineering/dbt_cloud_setup.md

<img width="682" alt="Screenshot 2023-06-29 at 7 28 35 AM" src="https://github.com/DataTalksClub/data-engineering-zoomcamp/assets/24155350/2c59d221-f0fb-4ccf-8b99-bf15b917c210">

**Comment by Victoriapm** [comment]
We do not own or maintain the streamlit app, can you move this issue to their repository? (there's an about section that explains this)
