### ISSUE TITLE
Timecodes for "DE Zoomcamp 6.3-What is kafka?"

### ISSUE THREAD

**Issue by dimzachar** [DataTalksClub/data-engineering-zoomcamp#385]
Youtube video: https://www.youtube.com/watchv=zPLZUDPi4AY

**Comment by dimzachar** [comment]
0:00:01 - Foreign music, Kafka streaming, data exchange
0:00:30 - Kafka's details, scaling, robustness, configurations explored
0:00:55 - Producers create, consumers consume, Kafka
0:01:24 - Dig deep into continuous stream of events
0:01:54 - Temperature recorded at specific time intervals
0:02:19 - Timestamps organize events, logs store data
0:02:48 - Logs store data, events structure messages
0:03:12 - Certain fields required, others not
0:03:39 - Key determines message partitioning, Kafka explained
0:04:02 - Topics, messages, events, Kafka, government, robustness
0:04:27 - Data replication ensures robustness and reliability
0:04:47 - Flexible stream processing system with Kafka
0:05:14 - Flexible, affordable data storage with scalability
0:05:36 - Kafka: popular for scalability and flexibility
0:06:01 - Retention and expiration for sustained messages
0:06:23 - Kafka provides robust data exchange
0:06:57 - Monolithic databases causing issues, microservices trending
0:07:27 - Many small apps form microservice architecture
0:07:58 - Accessible to all, but not scalable
0:08:30 - Microservices with increasing data need consistency
0:09:01 - Trust Kafka message, microservice reads, writes
0:09:30 - Multiple data sources for microservices
0:09:59 - CDC captures Kafka messages for microservices

**Comment by amitfrancis** [comment]
Updated! Thank you so much!
