### ISSUE TITLE
Timecodes for "DE Zoomcamp 1.4.2 - Using Github Codespaces for the Course"

### ISSUE THREAD

**Issue by mrcos-mrtinelli** [DataTalksClub/data-engineering-zoomcamp#406]
YouTube Video: https://youtu.be/XOSUt8Ih3zA?si=Nqm4aemLGUr0aPal

**Comment by mrcos-mrtinelli** [comment]
0:00 Intro to GitHub Codespaces
1:05 Create a Repo
1:47 Create New Codespace
2:54 Run Codespace Locally/Desktop
3:22 GitHub Codespaces Extension
3:57 Codespaces Overview and Features
5:02 Install Terraform
6:05 Jupyter Notebook
8:54 Running Docker, PostgreSQL Server, and pgAdmin
10:33 Commit changes and push to GitHub
11:50 pgAdmin

**Comment by alexeygrigorev** [comment]
@amitfrancis please add it

**Comment by amitfrancis** [comment]
Updated timecodes, thanks!
