### ISSUE TITLE
Issues with cohorts/2024 /01-docker-terraform

### ISSUE THREAD

**Issue by jmperafan** [DataTalksClub/data-engineering-zoomcamp#408]
I have found a couple of issues with the homework of the first week:

1. Question 4 says "Which was the pick up day with the largest trip distance?". But it is not obvious if you mean highest total (i.e. sum) or longest (i.e. max). Interestingly, both queries have exactly the same answer. 
2. The link to the Terraform exercises is broken: week_1_basics_n_setup/1_terraform_gcp/terraform

**Comment by ajmdz** [comment]
I suppose the link to (2) would be [this one](https://github.com/DataTalksClub/data-engineering-zoomcamp/tree/main/01-docker-terraform/1_terraform_gcp/terraform/). They changed `week_1_basics_n_setup/` to `01-docker-terraform/`. I'll try to create a PR for this.

**Comment by keenanandrew** [comment]
Another homework ambiguity question: question 6 asks for the 'largest tip'. 

Is that the largest tip in absolute terms, or as a percentage of the total fare amount?
