### ISSUE TITLE
Broken link in section 2.2.3: ETL: API to Postgres

### ISSUE THREAD

**Issue by edumunozsala** [DataTalksClub/data-engineering-zoomcamp#422]
Hi,
In section 2.2.3: ETL to Postgres, There is a resource called Sample loading block and the link is broken: https://github.com/mage-ai/mage-zoomcamp/blob/solutions/magic-zoomcamp/data_loaders/load_nyc_taxi_data.py

I think is the code to use in the Mage block to load data in the demo video and it'd be very helpful and I can't find any folder in the mage-zoomcamp repo to replace the broken link.

Thank you

**Comment by alexeygrigorev** [comment]
@mattppal

**Comment by mattppal** [comment]
Ah this was from the solutions that I removed. I will re-add

**Comment by mattppal** [comment]
Fixed 👍

**Comment by edumunozsala** [comment]
Nice! Thanks
