### ISSUE TITLE
Timecodes for "DE Zoomcamp 1.3.1 - Terraform Primer"

### ISSUE THREAD

**Issue by el-grudge** [DataTalksClub/data-engineering-zoomcamp#426]
YouTube Video: https://www.youtube.com/watch?v=s2bOYDCKl_M&list=PL3MmuxUbc_hJed7dXYoJw8DoCuVHhGEQb&index=11

**Comment by el-grudge** [comment]
0:00 Terraform concept 
1:44 Why use Terraform 
3:46 What Terraform is Not
5:39 What is / isn't covered in these videos
7:05 How Terraforom works
8:15 Providers 
9:10 Key commands

**Comment by MichaelShoemaker** [comment]
These have been added. Thank you!
