### ISSUE TITLE
Timecodes for "DE Zoomcamp 1.3.2 - Terraform Basics"

### ISSUE THREAD

**Issue by el-grudge** [DataTalksClub/data-engineering-zoomcamp#427]
YouTube Video: https://www.youtube.com/watch?v=Y2ux7gq3Z0o&list=PL3MmuxUbc_hJed7dXYoJw8DoCuVHhGEQb&index=12

**Comment by el-grudge** [comment]
0:00 Setting up a service account on GCP
4:15 Managing Keys
9:00 Creating main.tf file
12:14 Setting up credentials and providers
14:23 terraform init
15:37 Creating a storage bucket on GCP
21:13 terraform plan
22:44 terraform apply
24:54 terraform destroy
26:20 Summary

**Comment by Victoriapm** [comment]
hey @el-grudge thanks for adding this for all videos, you could actually comment the timecodes directly in the video and it will be accessible and clickable

**Comment by el-grudge** [comment]
@Victoriapm fyi comments added on youtube

**Comment by MichaelShoemaker** [comment]
Timecodes added
