### ISSUE TITLE
Confirmation email on homework submission

### ISSUE THREAD

**Issue by ai2ys** [DataTalksClub/data-engineering-zoomcamp#440]
Could a confirmation email get send when submitting the homework?

As discussed in the following Slack thread: https://datatalks-club.slack.com/archives/C01FABYF2RG/p1706036081478959

An additional benefit from a confirmation mail could be that participants will have less questions how they know if there homework was submitted successfully.

**Comment by alexeygrigorev** [comment]
Refer to https://github.com/DataTalksClub/course-management-platform/issues/2
