### ISSUE TITLE
Week 2 - Task stuck at up_for_retry

### ISSUE THREAD

**Issue by hoanghapham** [DataTalksClub/data-engineering-zoomcamp#61]
Hi,

I tried to run `data_intestrion_gcs_dag` from the webserver but the first task stuck at up_for_retry stage. When I tried to check the log this is the only thing I found:

![image](https://user-images.githubusercontent.com/13628076/152120406-96d75c56-b86d-4c06-adb2-1253c1947906.png)

However, I can still run this dag via the Airflow CLI. I'm not sure what's the problem here - I built the image  on two different machines, one worked fine, and one got stuck like this.

**Comment by alexeygrigorev** [comment]
Try nuking the whole thing and start with a clean slate 

```
docker-compose down -v --rmi all --remove-orphans
```

**Comment by hoanghapham** [comment]
HI Alexey, thanks for the suggestion. Turns out that the log subfolder use the full timestamp as the folder name, and my system does not allow creating a folder with colons 

```
airflow-worker_1     | [2022-02-02 11:52:12,923: ERROR/ForkPoolWorker-15] Failed to execute task [Errno 22] Invalid argument: '/opt/airflow/logs/data_ingestion_gcs_dag/download_dataset_task/2022-02-02T11:52:11.597940+00:00'.
airflow-worker_1     | Traceback (most recent call last):
airflow-worker_1     |   File "/usr/local/lib/python3.7/pathlib.py", line 1273, in mkdir
airflow-worker_1     |     self._accessor.mkdir(self, mode)
airflow-worker_1     | FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/logs/data_ingestion_gcs_dag/download_dataset_task/2022-02-02T11:52:11.597940+00:00'
```

This is weird because I can still create folders with colons in the name on a different partition, but not on the partition that I'm working with.

**Comment by alexeygrigorev** [comment]
that's interesting! happy to know you found out the root cause and a solution
