### ISSUE TITLE
Week 4 - DBT build ARGs not being correctly passed after FROM

### ISSUE THREAD

**Issue by jerdra** [DataTalksClub/data-engineering-zoomcamp#87]
Hey DataTalks zoompcamp team!

I'm not sure if I'm the only person having this issue but it looks like the Dockerfile file provided in Week 4 for building dbt-bigquery fails to build. Namely the `ARG`s defined at the beginning of the Dockerfile aren't made available during each part of the multi-stage build. 

I think each particular `ARG` needs to be defined after each `FROM` statement for it to be accessible during a particular build stage.

i.e:

```
...
FROM base as dbt-core
ARG dbt_core_ref=dbt-core@v1.0.1
RUN echo python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_core_ref}#egg=dbt-core&subdirectory=core" \
  && python -m pip install --no-cache-dir "git+https://github.com/dbt-labs/${dbt_core_ref}#egg=dbt-core&subdirectory=core"
```

The [Docker Docs on this behaviour](https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact) make a claim that you don't need to re-define a default value after `FROM` (i.e leave it as `ARG dbt_core_ref` but that hasn't worked on my system using `Docker 20.10.12`.

**Comment by alexeygrigorev** [comment]
Maybe try asking in Slack?
